TwitterMvc/Models/Question.cs
using System;

namespace TwitterMvc.Models
{
    public class Question
    {
        public Question()
        {
            
        }
        
        public Question(string senderId, string recieverId, string message)
        {
            SenderId = senderId;
            ReceiverId = recieverId;
            Message = message;
        }

        public int Id { get; set; }
        public string Message { get; set; }
        public DateTime SentTime { get; set; } = DateTime.Now;
        public string SenderId { get; set; }
        public CustomUser Sender { get; set; }
        public string ReceiverId { get; set; }
        public CustomUser Receiver { get; set; }
        public Answer Answer { get; set; }
    }
}

TwitterMvc/Controllers/QuestionAndAnswerController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TwitterMvc.Models;
using TwitterMvc.Services.Interfaces;

namespace TwitterMvc.Controllers
{
    public class QuestionAndAnswerController : Controller
    {
        private readonly IQuestionAndAnswerService _qnaService;
        private readonly UserManager<CustomUser> _userManager;

        public QuestionAndAnswerController(IQuestionAndAnswerService qnaService, UserManager<CustomUser> userManager)
        {
            _qnaService = qnaService;
            _userManager = userManager;
        }
        
        [HttpPost]
        public async Task<IActionResult> SendQuestion(string receiverId, string message)
        {
            var sender = await _userManager.GetUserAsync(User);
            var result = await _qnaService.SendQuestion(sender.Id, receiverId, message);
            
            return RedirectToAction("Index", "Profile", new { userId = receiverId });
        }

        [HttpGet]
        public async Task<IActionResult> Questions()
        {
            var user = await _userManager.GetUserAsync(User);
            var result = await _qnaService.GetQuestions(user.Id);

            if (result.Content.Count == 0) ViewBag.NoQuestionMessage = "You don't have any questions :(";
            
            return View(result.Content);
        }

        [HttpPost]
        public async Task<IActionResult> AnswerToQuestion(int questionId, string message)
        {
            var user = await _userManager.GetUserAsync(User);
            var result = await _qnaService.AnswerToQuestion(user.Id, questionId, message);
            
            return RedirectToAction("Questions");
        }
    }
}

TwitterMvc/Views/QuestionAndAnswer/Questions.cshtml
@model List<TwitterMvc.Dtos.QuestionAndAnswerDtos.GetQuestionDto>
@{
    string message = "";
}

@if (ViewBag.NoQuestionMessage != null)
{
    <div class="alert alert-secondary" role="alert">@ViewBag.NoQuestionMessage</div>
}

@foreach (var question in Model)
{
    <div class="post">
        <div class="post-title">
            @question.SenderName
        </div>
        <div class="post-text">
            @question.QuestionMessage
        </div>
        @using (Html.BeginForm("AnswerToQuestion", "QuestionAndAnswer", FormMethod.Post))
        {
            @Html.TextBoxFor(m => message, new { @class = "" })
            @Html.Hidden("questionId", question.Id);
            <button type="submit" class="btn btn-success">Answer</button>
        }
    </div>
}