TwitterMvc/Controllers/HomeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TwitterMvc.Data.Context;
using System.Linq;
using TwitterMvc.Dtos.UserDtos;
using TwitterMvc.Models;
using Microsoft.AspNetCore.Identity;
using TwitterMvc.Services.Interfaces;

namespace TwitterMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<CustomUser> _userManager;
        private readonly IFollowService _followService;

        public HomeController(AppDbContext context, UserManager<CustomUser> userManager, IFollowService followService)
        {
            _context = context;
            _userManager = userManager;
            _followService = followService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var loggedUser = await _userManager.GetUserAsync(User);
            if(loggedUser != null)
            {
                var following = await _followService.GetFollowing(loggedUser.Id);

                if (following.Succeeded)
                    ViewBag.Following = following.Content;
                else
                    ViewBag.Error = following.ErrorMessage;
            }

            var usersList = await _context.CustomUsers
                .Select(x => new UserListItemDto(x))
                .ToListAsync();

            return View(usersList);
        }
    }
}

TwitterMvc/Controllers/ProfileController.cs
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TwitterMvc.Dtos;
using TwitterMvc.Dtos.UserDtos;
using TwitterMvc.Models;
using TwitterMvc.Services.Interfaces;

namespace TwitterMvc.Controllers
{
    [Route("[controller]")]
    public class ProfileController : Controller
    {
        private readonly UserManager<CustomUser> _userManager;
        private readonly IPostService _postService;
        private readonly IMapper _mapper;
        private readonly IFollowService _followService;
        private readonly IQuestionAndAnswerService _qnaService;

        public ProfileController(UserManager<CustomUser> userManager, IPostService postService, IMapper mapper, IFollowService followService, IQuestionAndAnswerService qnaService)
        {
            _userManager = userManager;
            _postService = postService;
            _mapper = mapper;
            _followService = followService;
            _qnaService = qnaService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string userId)
        {
            var loggedUser = await _userManager.GetUserAsync(User);
            var profileUser = userId != null ? await _userManager.FindByIdAsync(userId) : loggedUser;

            if(loggedUser != null && loggedUser.Id != profileUser.Id)
            {
                var followed = await _followService.Followed(loggedUser.Id, profileUser.Id);
                if (followed.Succeeded)
                {
                    ViewBag.Followed = followed.Content;
                }
            }

            var followers = await _followService.GetFollowers(profileUser.Id);
            ViewBag.FollowersCount = followers.Succeeded ? followers.Content.Count : 0;

            var profile = new ProfileDto(profileUser);

            ViewBag.UserId = profileUser.Id;
            ViewBag.Avatar = $"/img/{profile.Gender}.png";
                
            var result = await _postService.GetPosts(profileUser.Id);
            if (result.Succeeded)
            {
                ViewBag.Posts = result.Content;
            }
            else
            {
                TempData["Error"] = result.ErrorMessage;
            }

            var qnaResult = await _qnaService.GetAnsweredQuestions(profileUser.Id);
            if (qnaResult.Succeeded)
            {
                ViewBag.Qna = qnaResult.Content;
            }

            return View(profile);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Post(PostDto postDto)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);

                await _postService.CreatePost(userId, postDto);
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpPost("EditPost")]
        public IActionResult EditPost(GetPostDto post)
        {
            var postData = _mapper.Map<PostDto>(post);
            ViewBag.PostId = post.Id;

            return View(postData);
        }

        [Authorize]
        [HttpPost("EditPost/{postId}")]
        public async Task<IActionResult> EditPost(int postId, PostDto postDto)
        {
            if(ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);

                var result = await _postService.EditPost(userId, postId, postDto);

                if (!result.Succeeded)
                {
                    TempData["Error"] = result.ErrorMessage;
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.PostId = postId;
            return View();
        }
        
        [Authorize]
        [HttpPost("{postId}")]
        public async Task<IActionResult> DeletePost(int postId)
        {
            var user = await _userManager.GetUserAsync(User);
            var result = await _postService.RemovePost(user.Id, postId);
        
            if (!result.Succeeded)
            {
                TempData["Error"] = result.ErrorMessage;
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

TwitterMvc/Views/Home/Index.cshtml
@using TwitterMvc.Enums;

@model List<TwitterMvc.Dtos.UserDtos.UserListItemDto>
@{
    string GetImg(GenderEnum gender)
    {
        return $"/img/{gender}.png";
    }
}

    <div class="row">
        <div class="col-md-8 mt-3 pr-3">
            <div class="home-title">Users</div>
            <div class="home-list p-4">
                <div class="row">
                    @foreach (var user in Model)
                    {
                        <div class="col-md-3">
                            <a class="profile-link" asp-controller="Profile" asp-action="Index" asp-route-userId="@user.Id">
                                <div class="profile-avatar">
                                    <img src="@GetImg(user.Gender)" />
                                    <div class="profile-avatar-info">
                                        <p class="profile-avatar-info-username">@user.Username</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="col-md-4 mt-3 pl-3">
            <div class="home-title">Following</div>
            <div class="home-list p-4">
                <div class="row">
                    @if (ViewBag.Following != null)
                    {
                        @foreach (var followingUser in ViewBag.Following)
                        {
                            <div class="col-md-6">
                                <a class="profile-link" asp-controller="Profile" asp-action="Index" asp-route-userId="@followingUser.Id">
                                    <div class="profile-avatar">
                                        <img src="@GetImg(followingUser.Gender)" />
                                        <div class="profile-avatar-info">
                                            <p class="profile-avatar-info-username">@followingUser.Username</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        }
                    }
                    else
                    {
                        <div class="alert alert-secondary" role="alert" style="margin: auto;">@ViewBag.Error</div>
                    }
                </div>
            </div>
        </div>
    </div>